name: SE
links:
  - name: Github
    target: /api/link/github
    iconName: github
  - name: Twitter
    target: /api/link/twitter
    iconName: twitter
  - name: Instagram
    target: /api/link/instagram
    iconName: instagram
  - name: Linkedin
    target: /api/link/linkedin
    iconName: linkedin
  - name: Mail
    target: mailto:samirettali@protonmail.com
    iconName: mail
  - name: Photographs
    target: /api/link/photographs
    iconName: camera
  - name: NFT
    target: /api/link/nft
    iconName: code
  - name: RSS
    target: /rss.xml
    iconName: rss
