baseURL = "https://samirettali.com/"

languageCode = "en-us"
title = "Samir's blog"

pygmentsStyle = "igor" # igor, lovelace, arduino, pastie
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses = true # new add

disableHugoGeneratorInject = true


[permalinks]
  blog = "/:filename/"

[menu]
  # [[menu.main]]
  #   name = "Posts"
  #   url = "/blog/"
  #   weight = 1
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 2

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome!"
  github = "samirettali"
  twitter = "samirettali"
  keybase = "samirettali"
