baseURL = "https://samirettali.com/"

languageCode = "en-us"
title = "Samir's blog"

pygmentsStyle = "lovelace" # igor, lovelace, arduino, pastie
pygmentsCodeFences = true
theme = "clean"
pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses = true # new add

disableHugoGeneratorInject = true


[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 2

[params]
  dateFormat = "Jan 2, 2006"
  github = "samirettali"
  twitter = "samirettali"
  mail = "ettali.samir@gmail.com"
  description="Hi, I'm Samir and I'm a Computer Science student living in Turin, Italy. I love programming and I play CTFs. I mainly post my writeups on the blog."
