baseURL = "https://samirettali.com/"

languageCode = "en-us"
title = "SE"

pygmentsStyle = "lovelace" # igor, lovelace, arduino, pastie
pygmentsCodeFences = true
theme = "codex"
pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses = true # new add

disableHugoGeneratorInject = true

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    title = "Blog"

  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/writeups/"
    title = "Writeups"

[params]
  dateFormat = "Jan 2, 2006"
  github = "samirettali"
  twitter = "samirettali"
  mail = "ettali.samir@gmail.com"
  description="Hi, I'm Samir and I'm a Computer Science student living in Turin, Italy. I love programming and I play CTFs. I mainly post my writeups on the blog."
