baseURL = "https://samirettali.com/"

languageCode = "en-us"
title = "Samir"
theme = "basics"

# Chroma Syntax Highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsStyle = "solarized-light"
# pygmentsUseClasses = true

[params]
    github = "samirettali"
    twitter = "samirettali"
    keybase = "samirettali"
