baseURL = "https://samirettali.com/"

languageCode = "en-us"
title = "Samir's blog"
theme = "hugo-theme"

[permalinks]
  blog = "/:filename/"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 2

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to my blog!"
  github = "samirettali"
  twitter = "samirettali"
  keybase = "samirettali"
