baseURL = "https://samirettali.com/"

languageCode = "en-us"
title = "Samir Ettali"

pygmentsStyle = "lovelace"
pygmentsCodeFences = true
theme = "clean"
hasCJKLanguage = false
pygmentsCodeFencesGuessSyntax = true
googleAnalytics = "UA-149325930-1"

disableHugoGeneratorInject = true

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    title = "Blog"

  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/writeups/"
    title = "Writeups"

[params]
  author = "Samir Ettali"
  description = "Hi, I'm Samir and I'm a Computer Science student living in Turin, Italy. I love programming and I play CTFs. I mainly post my writeups on the blog."
  dateFormat = "Jan 2, 2006"

  twitter = "samirettali"
  github = "samirettali"
  mail = "ettali.samir@gmail.com"

  enableRSS = true

  enableGoogleAnalytics = true
