name: SE
links:
  - name: Github
    href: /github
    iconName: github
  - name: Twitter
    href: /twitter
    iconName: twitter
  - name: Instagram
    href: /instagram
    iconName: instagram
  - name: Linkedin
    href: /linkedin
    iconName: linkedin
  - name: Mail
    href: mailto:samirettali@protonmail.com
    iconName: mail
  - name: Photographs
    href: /photographs
    iconName: camera
  # - name: NFT
  #   href: https://rarible.com/samirettali
  #   iconName: code
  - name: RSS
    href: /rss.xml
    iconName: rss
