name: Build site every hour

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: pulimento/github-action-hugo-deploy-to-firebase@master
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
